name: 📦 Continuous Deployment (CD)
description: Deploy new version to instance

runs:
  using: "composite"
  steps:
    - name: 🐋 Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: 🔐 Login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 🏗️ Build and Publish
      shell: bash
      run: |
        docker buildx build -t banking-backend:${{  github.ref_name }} -t banking-backend:latest --load .

        docker image tag banking-backend ghcr.io/simplytest/banking-backend
        docker push -a ghcr.io/simplytest/banking-backend

    - name: 📦 Deploy
      uses: appleboy/ssh-action@55dabf81b49d4120609345970c91507e2d734799
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}

        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

        script: |
          docker stop Banking-Backend-Demo || true
          docker rm Banking-Backend-Demo || true

          docker pull ghcr.io/simplytest/banking-backend:latest
          docker run -d -p 5005:5005 -e "SIMPLYTEST_DEMO=ON" --rm --name=Banking-Backend-Demo ghcr.io/simplytest/banking-backend:latest
