on:
  workflow_dispatch:
  push:
    tags:
      - "*"

name: ☕ Build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🐋 Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏗️ Build and Publish
        run: |
          docker buildx build --tag banking-backend --load .

          docker image tag banking-backend ghcr.io/simplytest/banking-backend
          docker push ghcr.io/simplytest/banking-backend:latest
