on:
  push:
  pull_request:
  workflow_dispatch:

name: 🧪 Run Tests

jobs:
  test:
    runs-on: ubuntu-latest
    container: fedora:38

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🏗️ Setup Dependencies
        run: |
          dnf install -y java-17-openjdk maven git

      - name: 🧪 Unit Tests
        run: |
          mvn test -Dtest="CucumberUnitTest" -Dsurefire.failIfNoSpecifiedTests=false

      - name: 📋 Unit Test Report
        uses: phoenix-actions/test-reporting@v8
        if: success() || failure()
        with:
          name: 📋 Unit Test Report
          reporter: java-junit
          path: "**/*CucumberUnitTest.xml"
