on:
  push:
  pull_request:
  workflow_dispatch:

name: 🧪 Continuous Integration

jobs:
  ci:
    runs-on: ubuntu-latest
    container: fedora:38

    steps:
      - name: 🏗️ Setup Dependencies
        run: |
          dnf install -y java-17-openjdk maven git

      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🛠️ Checkout Workaround
        # The Checkout GitHub action has problems when running inside of a docker container (as we do).
        # see: https://github.com/actions/checkout/issues/363
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: 🧪 Unit Tests
        run: |
          mvn test -Dtest="CucumberUnitTest" -Dsurefire.failIfNoSpecifiedTests=false

      - name: 📋 Unit Test Report
        uses: phoenix-actions/test-reporting@v8
        if: success() || failure()
        with:
          name: 📋 Unit Test Report
          reporter: java-junit
          path: "**/*CucumberUnitTest.xml"

      - name: 🧪 Integration Tests
        run: |
          mvn test -Dtest="CucumberIntegrationTest" -Dsurefire.failIfNoSpecifiedTests=false

      - name: 📋 Integration Test Report
        uses: phoenix-actions/test-reporting@v8
        if: success() || failure()
        with:
          name: 📋 Integration Test Report
          reporter: java-junit
          path: "**/*CucumberIntegrationTest.xml"

      - name: 📦 Deploy
        if: success() && startsWith(github.ref, 'refs/tags/v')
        uses: ./.github/actions/cd
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}

          user: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

          repo-user: ${{ github.actor }}
          repo-password: ${{ secrets.GITHUB_TOKEN }}

          tag: ${{ github.ref_name }}
