on:
  push:
  pull_request:
  workflow_dispatch:

name: 🧪 Run Tests

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:38

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🏗️ Setup Dependencies
        run: |
          dnf install -y java-17-openjdk maven

      - name: 🧪 Cucumber Tests
        run: |
          mvn test
